### ISSUE TITLE
Problem using this library and AndroidAnnotation 4.3.0

### ISSUE THREAD

**Issue by kaiyan910** [hotchemi/PermissionsDispatcher#334]
## Overview

Hi, currently I am using AndroidAnnotation with PermissionsDispatcher, AA version using 4.2.0 work great but when I upgrade to 4.3.0, PermissionsDispatcher can not create 'xxxActivityPermissionsDispatcher' and show 'Error:(105, 29) error: cannot find symbol variable 'xxxActivityPermissionsDispatcher'

I am not sure whether I should post it here or the plugin page, thanks in advance.

### Expected
create 'xxxActivityPermissionsDispatcher'

### Actual
show 'Error:(105, 29) error: cannot find symbol variable 'xxxActivityPermissionsDispatcher'

## Environment
gradle using classpath 'com.android.tools.build:gradle:2.3.3'

AAVersion = 4.3.0
- compile 'com.github.hotchemi:permissionsdispatcher:2.4.0'
- annotationProcessor 'com.github.hotchemi:permissionsdispatcher-processor:2.4.0'
- compile "org.androidannotations:androidannotations-api:$AAVersion"
- annotationProcessor "org.androidannotations:androidannotations:$AAVersion"
- annotationProcessor "org.androidannotations:ormlite:$AAVersion"
- compile "org.androidannotations:ormlite-api:$AAVersion"
- annotationProcessor "org.androidannotations:otto:$AAVersion"
- annotationProcessor 'com.github.AleksanderMielczarek:AndroidAnnotationsPermissionsDispatcherPlugin:0.1.0'`

## Reproducible steps

use AndroidAnnotation 4.3.0 with permissionsdispatcher 2.4.0

**Comment by hotchemi** [comment]
@kaiyan910 thx, are you using https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin?
cc: @AleksanderMielczarek

**Comment by kaiyan910** [comment]
Yes, I am

**Comment by hotchemi** [comment]
ic. let us investigate a bit.

**Comment by AleksanderMielczarek** [comment]
Hi,

@hotchemi I cannot reproduce this issue. @kaiyan910 can you provide minimal example project showing the issue?
Also I've just release a new version (1.0.0) with updated dependencies but I don't think this will change anything.

**Comment by kaiyan910** [comment]
It's wired with the same project I can build it on MAC but not in Windows.
Then I think it is the problem on my Windows's Android Studio? 

I will have a try on the new version, @AleksanderMielczarek thanks for your support!

**Comment by hotchemi** [comment]
> It's wired with the same project I can build it on MAC but not in Windows.

Oh ic, then that might be the platform problem with AS or annotation processing...could you possibly test without AndroidAnnotations(I mean pure PermissionsDispatcher)?

Anyway I'm really thankful for your dedicated work @kaiyan910 @AleksanderMielczarek 🙇

**Comment by kaiyan910** [comment]
Seems that the problem came from the Gilde 4.0 compiler

annotationProcessor 'com.github.bumptech.glide:compiler:4.0.0-RC1'
compile 'com.github.bumptech.glide:glide:4.0.0-RC1'

after I remove the dependency it is able to generate the class, but still don't understanding why MAC is ok

**Comment by AleksanderMielczarek** [comment]
@kaiyan910 @hotchemi just added Glide to dependencies just for test and for me it's working on Windows 10.
https://github.com/AleksanderMielczarek/AndroidAnnotationsPermissionsDispatcherPlugin/tree/glide-test

**Comment by hotchemi** [comment]
@kaiyan910 umm, is the problem only via Android Studio? if you build an app from command line(gradle) what would be happened?

**Comment by hotchemi** [comment]
Anyway, it seems it's not a problem of the library itself so let me close the issue.
