### ISSUE TITLE
PermissionsDispatcher Error

### ISSUE THREAD

**Issue by luis-goncalves** [hotchemi/PermissionsDispatcher#336]
Hi after updating from 2.3.1 to 2.4.0 cleaning and rebuilding the project I get the following error
cannot find symbol method getTargetSdkVersion(Activity) in the PermissionsDispatcher generated file for now I reverted back to 2.3.1 and everything works fine.
Since I can't find anything different in the usage example I'm assuming that the getTargetSdkVersion is missing in 2.4.0 or there's something more I need to change?
Currently targeting Sdk Version 23.
Thanks.

**Comment by shiraji** [comment]
`PermissionUtils#getTargetSdkVersion` is removed since PermissionsDispatcher don't use it anymore.

https://github.com/hotchemi/PermissionsDispatcher/pull/307

**Comment by hotchemi** [comment]
@luis-goncalves as @shiraji mentioned we removed `getTargetSdkVersion` in 2.4.0. so could you try `./gradlew clean` before building?

**Comment by luis-goncalves** [comment]
Hi.
Thank for replying.
I try clean and clean build cache;
Invalidate cache/restart android studio;
Deleting gradle caches and the compiled code;
Removing the reference and repeating;
No luck.
Since 2.3.1 works fine I'll keep using it, I will try a new project with 2.4.0 when possible.
Thanks anyway.

**Comment by hotchemi** [comment]
@luis-goncalves do you mean you could solve the problem?

**Comment by shiraji** [comment]
Do you use `PermissionUtils#getTargetSdkVersion` somewhere in your project?

**Comment by luis-goncalves** [comment]
@hotchemi For now I will keep the using version 2.3.1, it's working fine.
@shiraji Only PermissionsDispatcher uses PermissionUtils#getTargetSdkVersion.

**Comment by hotchemi** [comment]
@luis-goncalves ok? if you have any questions feel free to ask us.
